name: single
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotli-python=1.0.9=py39h5a03fae_7
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2025.1.31=hbcca054_0
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cffi=1.15.0=py39h4bc2ebd_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_1
  - cudatoolkit=11.6.0=hecad31d_10
  - debugpy=1.8.11=py39h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9e=h166bdaf_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=12_linux64_mkl
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=12_linux64_mkl
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=hecacb30_2
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.6=he412f7d_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.3=h166bdaf_0
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=23.0.1=py39h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.50=pyha770c72_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.7=hf930737_3_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.9=2_cp39
  - pytorch-mutex=1.0=cuda
  - pyzmq=26.2.0=py39h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - setuptools=67.8.0=py39h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py39_cu116
  - tornado=6.1=py39hb9d737c_3
  - traitlets=5.14.3=pyhd8ed1ab_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.19.0=py39h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==2.1.0
      - accelerate==1.3.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - albumentations==1.3.1
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - array-record==0.5.1
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.1.0
      - bitsandbytes==0.45.2
      - cachetools==5.5.2
      - cfgv==3.4.0
      - click==8.1.8
      - colorama==0.4.6
      - compressai==1.2.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - diffusers==0.32.2
      - distlib==0.3.9
      - dm-tree==0.1.8
      - einops==0.8.0
      - einx==0.3.0
      - etils==1.5.2
      - executing==2.2.0
      - facexlib==0.3.0
      - fastapi==0.115.8
      - ffmpy==0.5.0
      - filelock==3.17.0
      - filterpy==1.4.5
      - flatbuffers==25.2.10
      - fonttools==4.55.8
      - frozendict==2.4.6
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - future==1.0.0
      - gast==0.6.0
      - gcsfs==2025.3.0
      - git-filter-repo==2.47.0
      - google-api-core==2.24.2
      - google-auth==2.38.0
      - google-auth-oauthlib==1.2.1
      - google-cloud-core==2.4.3
      - google-cloud-storage==3.1.0
      - google-crc32c==1.7.0
      - google-pasta==0.2.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.69.2
      - gradio==3.50.0
      - gradio-client==0.6.1
      - grpcio==1.70.0
      - h11==0.14.0
      - h5py==3.13.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.28.1
      - icecream==2.1.4
      - identify==2.6.6
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - jinja2==3.1.5
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - keras==3.9.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - libclang==18.1.1
      - lightning==2.5.0.post0
      - lightning-utilities==0.12.0
      - llvmlite==0.43.0
      - lmdb==1.6.2
      - loguru==0.7.3
      - lpips==0.1.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - multidict==6.1.0
      - namex==0.0.8
      - narwhals==1.25.1
      - networkx==3.2.1
      - ninja==1.11.1.3
      - nodeenv==1.9.1
      - numba==0.60.0
      - numpy==1.24.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - openai-clip==1.0.1
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.14.1
      - orjson==3.10.15
      - pandas==2.2.3
      - pillow==10.4.0
      - pluggy==1.5.0
      - pre-commit==4.1.0
      - promise==2.3
      - propcache==0.2.1
      - proto-plus==1.26.1
      - protobuf==3.20.3
      - psutil==6.1.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyiqa==0.1.13
      - pyparsing==3.2.1
      - pytest==8.3.4
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.0.post0
      - pytorch-msssim==1.0.0
      - pytz==2025.1
      - pyyaml==6.0.2
      - qudida==0.0.4
      - referencing==0.36.2
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - rich==13.9.4
      - rpds-py==0.22.3
      - rsa==4.9
      - safetensors==0.5.2
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.9.3
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sniffio==1.3.1
      - starlette==0.45.3
      - sympy==1.13.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-datasets==4.9.3
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.16.1
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - timm==1.0.14
      - tokenizers==0.15.2
      - toml==0.10.2
      - tomli==2.2.1
      - torch==2.1.0
      - torch-geometric==2.6.1
      - torcha==0.1
      - torchac==0.9.3
      - torchmetrics==1.6.1
      - torchvision==0.16.0
      - tqdm==4.67.1
      - transformers==4.37.2
      - triton==2.1.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - uvicorn==0.34.0
      - vector-quantize-pytorch==1.21.7
      - virtualenv==20.29.1
      - websockets==11.0.3
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xformers==0.0.23
      - yapf==0.43.0
      - yarl==1.18.3
      - zipp==3.21.0
prefix: /root/miniconda3/envs/single
